name: Create PR
on:
  pull_request:
    branches:
      - opened

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set base branch as 'develop'
        run: |
          # 'GITHUB_REF' 변수에서 PR의 기본 브랜치를 추출합니다.
          base_branch=${GITHUB_REF#refs/pull/*/merge}
          base_branch=${base_branch#refs/heads/}

          # PR의 기본 브랜치를 'develop'으로 설정합니다.
          git checkout "${base_branch}"
          git branch --set-upstream-to=origin/develop
          git pull

      - name: Set PR title as branch name
        run: |
          # 'GITHUB_REF' 변수에서 PR의 브랜치 이름을 추출합니다.
          branch_name=${GITHUB_REF#refs/heads/}

          # PR 제목을 브랜치 이름으로 설정합니다.
          echo "PR 제목: $branch_name" >> pr_title.txt

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: $(cat pr_title.txt)
